# Generated by Django 4.2.4 on 2023-08-26 14:51

from pathlib import Path
import environ
import os

from django.db import migrations


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()

    env = environ.Env()
    BASE_DIR = Path(__file__).resolve().parent.parent.parent
    environ.Env.read_env(os.path.join(BASE_DIR, 'envs', '.env'))

    DJANGO_SU_NAME = env('DJANGO_SU_NAME')
    DJANGO_SU_EMAIL = env('DJANGO_SU_EMAIL')
    DJANGO_SU_PASSWORD = env('DJANGO_SU_PASSWORD')

    User.objects.create_superuser(
        username=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_superuser)
    ]
