# Generated by Django 4.2.4 on 2023-08-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nazwa', max_length=150, verbose_name='nazwa')),
            ],
            options={
                'verbose_name': 'Typ formularza',
                'verbose_name_plural': 'Typy formularza',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa', max_length=250, verbose_name='Nazwa')),
            ],
            options={
                'verbose_name': 'Część',
                'verbose_name_plural': 'Część',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowano')),
                ('title', models.CharField(help_text='Tytuł', max_length=200, verbose_name='Tytuł')),
                ('doctor_text', models.TextField(blank=True, help_text='Dla lekarza', null=True, verbose_name='Dla lekarza')),
                ('patient_text', models.TextField(blank=True, help_text='Dla pacjenta', null=True, verbose_name='Dla pacjenta')),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
                ('form_type', models.ForeignKey(blank=True, help_text='formularz', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='visit.formtype', verbose_name='formularz')),
            ],
            options={
                'verbose_name': 'Tekst',
                'verbose_name_plural': 'Teksty',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(help_text='Kolejność', verbose_name='Kolejność')),
                ('diagnosis', models.ForeignKey(help_text='Rozpoznanie', on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='visit.diagnosis', verbose_name='Rozpoznanie')),
                ('part', models.ForeignKey(help_text='Część', on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='visit.part', verbose_name='Część')),
                ('text', models.ForeignKey(help_text='Tekst', on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='visit.text', verbose_name='Tekst')),
            ],
            options={
                'verbose_name': 'Przypisanie',
                'verbose_name_plural': 'Przypisanie',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_choice', models.TextField(help_text='Dla lekarza', max_length=500, verbose_name='Dla lekarza')),
                ('patient_choice', models.TextField(help_text='Dla pacjenta', max_length=500, verbose_name='Dla pacjenta')),
                ('priority', models.IntegerField(help_text='Kolejność', verbose_name='Kolejność')),
                ('text', models.ForeignKey(help_text='Text', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='visit.text', verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Wybór',
                'verbose_name_plural': 'Wybory',
            },
        ),
    ]
