# Generated by Django 4.2.4 on 2023-09-11 18:05

from django.db import migrations

formtype_dict = {
    'text': 'tylko text- wypełnij tytuł, dla lekarza i dla pacjenta',
    'checkbox_combined': 'checkbox połączone- wypełnij tytuł, dla lekarza, dla pacjenta oraz wybory',
    'checkbox': 'checkbox osobno- wypełnij tytuł, dla lekarza, dla pacjenta oraz wybory',
    'fill_text': 'text i dane z formularza- wypełnij tytuł, dla lekarza i dla pacjenta',
    'fill_text_choices': 'text i kilka formularzy - wypełnij tytuł, dla lekarza, dla pacjenta oraz wybory',
    'checkbox_fill_text': 'text, checkbox i kilka formularzy - wypełnij tytuł, dla lekarza, dla pacjenta oraz wybory',
    'radio': 'radio - wypełnij tytuł, dla lekarza, dla pacjenta oraz wybory',
}


def generate_formtype(apps, schema_editor):
    FormType = apps.get_model('visit', 'FormType')

    for name, info in formtype_dict.items():
        FormType.objects.create(name=name, info=info)


def delete_formtype(apps, schema_editor):
    FormType = apps.get_model('visit', 'FormType')

    for formtype in FormType.objects.filter(id__lte=len(formtype_dict)):
        formtype.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('visit', '0003_formtype_info'),
    ]

    operations = [
        migrations.RunPython(generate_formtype, delete_formtype)
    ]
