# Generated by Django 4.2.4 on 2023-09-01 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0002_alter_patient_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zmodyfikowano')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Rozpoznanie')),
                ('interview', models.TextField(blank=True, null=True, verbose_name='Wywiad')),
                ('examination', models.TextField(blank=True, null=True, verbose_name='Badanie')),
                ('recommendations', models.TextField(blank=True, null=True, verbose_name='Zalecenia')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Rozpoczęcie wizyty')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Zakończenie wizyty')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Wizytz usunięta')),
                ('doctor', models.ForeignKey(default=2, help_text='lekarz', on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to=settings.AUTH_USER_MODEL, verbose_name='lekarz')),
                ('patiet', models.ForeignKey(help_text='pacjent', on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to='patient.patient', verbose_name='pacjent')),
            ],
            options={
                'verbose_name': 'wizyta',
                'verbose_name_plural': 'wizyty',
            },
        ),
    ]
